config/routes.rb
Brouzouf::Application.routes.draw do

  resources :bids

    
  resources :bets do
  
    member do
      post 'set_bet_open', 'set_bet_close', 'set_bet_creation', 'make_a_bid', 'close_bid'
      get  'close'
    end

    resources :choices, :only => [:new, :create, :update, :destroy, :edit]

  end

  get "home/index"

  devise_for :users do
  
    get 'users', :to => 'users#index', :as => :user_root # Rails 3
    match '/users/show/:id', :to => 'users#show',    :as => :user,         :via => :get
    #match '/users/list', :controller => '/list'
    match '/users/list' => 'users#list', :via => :get

  end

 # resources :users do
 #   collection do
 #     get 'list'
 #   end
 # end

  root :to => "home#index"

  
end

app/models/bet.rb
class Bet < ActiveRecord::Base
  belongs_to :user
  has_many :choices
  has_one :choice

  after_save :add_brouzouf

  def expired?
    expiration_date < Time.now
  end

  def open?
    state == 'OPEN'
  end

  def need_to_be_closed?
    expired? && open?
  end

  def editable?
    state == 'CREATION'
  end

  def closed?
    state == 'CLOSED'
  end


  def ratio_for_this_choice(id_choice)
     return  loosing_brouzouf(id_choice) / winning_brouzouf(id_choice)
  end


  # summ brouzouf bids in other choices
  def loosing_brouzouf(id_choice)
    Bid.where("bet_id = ? and choice_id != ?", self.id, id_choice).sum(:brouzouf)
  end

  def winning_brouzouf(id_choice)
    Bid.where("bet_id = ? and choice_id = ?", self.id, id_choice).sum(:brouzouf)
  end


  #TODO put in database
  def total_brouzouf
     Bid.where(:bet_id => this.id).sum(:brouzouf)
  end

  private

  def add_brouzouf
    logger.debug "Check if user just closed the bet then add brouzouf"

    if (state_was == "OPEN" and closed?)
      logger.debug "Bet is now CLOSED"

      raise "A closed Bet need a choice" if !self.choice


      Bid.where(:choice_id => self.choice.id).each do |bid|
        logger.debug "1 more brouzouf for " + user.name
        user = bid.user
        user.brouzouf = user.brouzouf + bid.brouzouf * (1 + ratio_for_this_choice(self.choice.id))
        user.save
      end

    end

  end


end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  

  before_filter :authenticate_user!, :except => [:show, :index]
  
  
  # GET /bets
  def index
    @bets = Bet.all
  end

  # GET /bets/1
  def show
    @bet = Bet.find(params[:id])
  end

  # GET /bets/new
  def new
    @bet = Bet.new
  end

  # GET /bets/1/edit
  def edit
    @bet = Bet.find(params[:id])
    
    if(@bet.user != current_user)
      redirect_to( user_root_url, :alert => "You don't have rigth to modify this bet.")
    end  
      
  end

  # POST /bets
  def create
    @bet = Bet.new(params[:bet])

    # associate connected user with newly created bet
    @bet.user = current_user

    if @bet.save
      #redirect_to :action => "new", :id => @bet.id
      redirect_to(new_bet_choice_url(@bet.id) , :notice => 'Bet was successfully created, Add a choice.')
    else
      render :action => "new"
    end
  end

  # PUT /bets/1
  def update
    @bet = Bet.find(params[:id])

    if @bet.update_attributes(params[:bet])
      redirect_to(user_root_url, :notice => 'Bet was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /bets/1
  def destroy
    @bet = Bet.find(params[:id])
    @bet.destroy

    redirect_to(user_root_url)
  end

  def set_bet_open
    logger.debug "Set the bet's state to OPEN"
    bet = Bet.find(params[:id])
    bet.state = "OPEN"

    if bet.save
      redirect_to(user_root_url, :notice => bet.title + ' was opened.')
    else
      render :action => "edit"
    end

  end

  def set_bet_close
    logger.debug "Set the bet's state to CLOSE"

    bet = Bet.find(params[:id])
    bet.state = "CLOSE"

    if bet.save
      redirect_to(user_root_url, :notice => bet.title + ' was closed.')
    else
      render :action => "edit"
    end
  end

  def set_bet_creation
    logger.debug "Set the bet's state to CREATION"
    bet = Bet.find(params[:id])
    bet.state = "CREATION"

    if bet.save
      redirect_to(user_root_url, :notice => bet.title + ' was in creation mode again.')
    else
      render :action => "edit"
    end
  end


  def make_a_bid
    logger.debug "Current User make a bid"

    choice = Choice.find(params[:choice_id])

    bid = Bid.new()
    bid.user = current_user
    bid.choice = choice
    bid.bet = choice.bet
    bid.brouzouf = 1

    if(bid.save)
      redirect_to(bet_url(choice.bet.id), :notice => 'Your bid was successfully saved')
    else
      redirect_to(bet_url(choice.bet.id), :warn => 'Error while saving your bid')
    end

  end


  def close
    logger.debug "Closing bet"
    @bet = Bet.find(params[:id])
  end

  def close_bid
    logger.debug "Closing bet with winning bid"

    bet = Bet.find(params[:id])

    bet.state = 'CLOSED'

    bet.choice_id = :choice_id

    bet.closed_at = Time.now

    #TODO update winnings for users that had a bid on this choice

    if(bet.save)
      redirect_to(user_root_url, :notice => 'Your bet was successfully closed')
    end


  end
  
  
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_choices.html.erb
<%if @bet.choices.count == 0 %>
	<p>No choice for this bet.</p>
<%else%>
	<% @bet.choices.each do |choice| %>
        <% unless choice.id.nil? %>
            <ul>
                <li><%=choice.description%> - <%= link_to 'Edit', edit_bet_choice_url(@bet, choice) %></li>
            </ul>
        <% end %>
	<%end%>
<%end%>

app/views/bets/_form.html.erb
<%= form_for(@bet) do |f| %>
  <% if @bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% @bet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



   <div class="field">
    Status : <%=@bet.state %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :expiration_date %>
    <%= f.datetime_select :expiration_date %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bets/_list.html.erb
<table class="table table-striped table-bordered table-condensed">
	  <tr>
    <th align="left">Title</th>
    <th align="left">Description</th>
    <th align="left">Remaining time</th>
    <th align="left">User</th>
  </tr>

<% @bets.each do |bet| %>
<% if bet.state == 'OPEN' && bet.expiration_date > Time.now%>
  <tr>
    <td><%= link_to bet.title, bet %><br/>
	    <%= link_to bet.title, bet_path(bet, :anchor => "disqus_thread") %></td>
    <td><%= bet.description %></td>
    <td><%= distance_of_time_in_words(Time.now,bet.expiration_date) %></td>
    <td><%= link_to bet.user.name, user_path(bet.user) %></td>
  </tr>
<% end %>
<% end %>
</table>

<script type="text/javascript">
	var disqus_developer = 0; // developer mode is off
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'brouzouf'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>

app/views/bets/close.html.erb
<h1>Closing bet</h1>
<h1><%= @bet.title %></h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @bet.description %>
</p>

<p>
  <b>Expiration date:</b>
  <%= @bet.expiration_date %>
</p>

<h2>Choices</h2>

<%= form_tag(:controller => "bets", :action => "close_bid", :method => "post") do %>

    <% nb_bids=0 %>
    <ul class="choices">
        <% @bet.choices.each do |choice| %>

            <li>
                <%= radio_button_tag(:choice_id, choice.id, true) %>
                <%= label_tag(:age_child, choice.description) %>
                (<%= pluralize(choice.bids.count, 'bid') %>)

            </li>

        <%end%>
    </ul>

    <%= submit_tag("Close Bet") if @bet.open? %>

<%end%>

app/views/bets/edit.html.erb
<h1>Editing bet</h1>

<%= render 'form' %>

<%if @bet.state == "CREATION" %>
    <%= form_tag(:controller => "bets", :action => "set_bet_open", :method => "post") do %>
        <%= submit_tag("Open Bet") %>
    <%end%>
<%end%>

<h2>Choices</h2>

<%= link_to "Add Choice for this bet", new_bet_choice_url(@bet)  %>

<%= render 'choices' %>

<br/>

app/views/bets/index.html.erb
<h1>Listing bets</h1>

    <%= render 'list' %>

<br />

app/views/bets/new.html.erb
<h1>New bet</h1>

<%= render 'choices' %>

<%= render 'form' %>

<%= link_to 'Back', user_root_path %>

app/views/bets/show.html.erb
<h1><%= @bet.title %></h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @bet.description %>
</p>

<p>
  <% if @bet.closed? %>
    <b>Bet closed</b>
  <% else %>
    <b>Expiration :</b>
      <%= distance_of_time_in_words(Time.now, @bet.expiration_date) %>
  <% end %>
</p>

<p>
  <b>User:</b>
  <%= link_to @bet.user.name, user_path(@bet.user)  %>
</p>


<h2>Choices</h2>


<div class="row">
<% if @bet.choices.count == 0 %>
	<p>No choice for this bet.</p>
<% else %>

    <% if !@bet.closed? %>

        <%= form_tag(:controller => "bets", :action => "make_a_bid", :method => "post") do %>

            <div class="twelve columns">
                <div class="seven columns">
                    <% @bet.choices.each do |choice| %>

                        <div>
                            <%= radio_button_tag :choice_id, choice.id, true %>
                            <%= choice.description %> (
                            <%= pluralize(choice.bids.count, 'bid') %>
                            <% if (choice.bids.count > 0) %> |
                              ratio : <%= sprintf( "%5.2f" , (1 + @bet.ratio_for_this_choice(choice.id))) %>
                            <% end %>
                            )
                        </div>

                    <% end %>
                </div>

                <% if user_signed_in? %>
                    <div class="four columns">

                        <% if current_user.brouzouf > 0 %>
                            <%= submit_tag("Make a bid", :class => "nice_button") if @bet.state == "OPEN" %>
                        <% else %>
                            You have no more brouzouf !
                        <% end %>
                    </div>
                </div>
            <% else %>
                </div>
                <div class = "row"></div>
                    <div class="alert">You have to <%= link_to 'create an account', new_user_registration_path %> or <%= link_to 'sign in', new_user_session_path %> to participate.</div>
                </div>

            <% end %>

        <% end %>

    <% else %>

          <ul class="twelve columns">
                <% @bet.choices.each do |choice| %>
	    		    <li class="<%= "winner" if @bet.choice.id == choice.id%>">
                      <span>
                        <%= choice.description %>
                      </span>
                        (<%= pluralize(choice.bids.count, 'bid') %>)
                    </li>
	            <%end%>
            </ul>

    <% end %>
</row>
<%end%>


<div id="disqus_thread"></div>
<script type="text/javascript">
	var disqus_developer = 0; // developer mode is off
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'brouzouf'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>