config/routes.rb
Brouzouf::Application.routes.draw do

  resources :bids

    
  resources :bets do
  
    member do
      post 'set_bet_open', 'set_bet_close', 'set_bet_creation', 'make_a_bid', 'close_bid'
      get  'close'
    end

    resources :choices, :only => [:new, :create, :update, :destroy, :edit]

  end

  get "home/index"

  devise_for :users do
  
    get 'users', :to => 'users#index', :as => :user_root # Rails 3
    match '/users/show/:id', :to => 'users#show',    :as => :user,         :via => :get
    #match '/users/list', :controller => '/list'
    match '/users/list' => 'users#list', :via => :get

  end

 # resources :users do
 #   collection do
 #     get 'list'
 #   end
 # end

  root :to => "home#index"

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :login, :email, :password, :password_confirmation, :remember_me

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'name'
  attr_accessor :login

  has_many :bets, :order => "created_at"
  has_many :bids, :order => "created_at"


  def self.find_record(login)
    where(["name = :value OR email = :value", {:value => login}]).first
  end

  def expired_bets
    self.bets.where("expiration_date < ? AND state = 'OPEN' ", Time.now)
  end

  def open_bets
    self.bets.where("expiration_date > ? AND state = 'OPEN' ", Time.now)
  end

  def draft_bets
    self.bets.where("state = 'CREATION' ", Time.now)
  end

  def closed_bets
    self.bets.where("state = 'CLOSE' ", Time.now)
  end

  protected

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(name) = :value OR lower(email) = :value", {:value => login.downcase}]).first
  end

  # Attempt to find a user by it's email. If a record is found, send new
  # password instructions to it. If not user is found, returns a new user
  # with an email not found error.
  def self.send_reset_password_instructions(attributes={})
    recoverable = find_recoverable_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    recoverable.send_reset_password_instructions if recoverable.persisted?
    recoverable
  end

  def self.find_recoverable_or_initialize_with_errors(required_attributes, attributes, error=:invalid)
    (case_insensitive_keys || []).each { |k| attributes[k].try(:downcase!) }

    attributes = attributes.slice(*required_attributes)
    attributes.delete_if { |key, value| value.blank? }

    if attributes.size == required_attributes.size
      if attributes.has_key?(:login)
        login = attributes.delete(:login)
        record = find_record(login)
      else
        record = where(attributes).first
      end
    end

    unless record
      record = new

      required_attributes.each do |key|
        value = attributes[key]
        record.send("#{key}=", value)
        record.errors.add(key, value.present? ? error : :blank)
      end
    end
    record
  end



end

app/controllers/users_controller.rb
class UsersController < Devise::SessionsController

  def create
    super
  end

  #user homepage
  def index
    logger.debug 'User HomePage actions'
    @user = current_user
  end

  def show
    logger.debug 'Public user display'
    @user = User.find(params[:id])
  end

  def list
    @bidders = User.find(:all, :order => "brouzouf desc")
  end

end

app/views/users/_show_bet.html.erb
<tr>
    <td><%= link_to bet.title, bet_path(bet) %> </td>
    <td>
        <% if bet.open? %>
            <%=link_to "Close", close_bet_path(bet) %>,
        <% end %>
        <% if bet.editable? %>
            <%=link_to "Edit", edit_bet_path(bet) %>,
        <% end %>
        <%= link_to 'Destroy', bet, :confirm => 'Are you sure?', :method => :delete %>
    </td>
</tr>

app/views/users/_show_bets.html.erb
<% if (user.expired_bets.count > 0) %>


      <% if user == current_user%>
        <div class="alert alert-block alert-info fade in">      
	        <a href="" class="close" data-dismiss="alert">&times;</a>
          <h4 class="alert-heading">Hi <%= user.name %> !</h4>
          <p>You have <%= pluralize(user.expired_bets.count, 'bet') %> that needs to be closed !</p> 
					<% user.expired_bets.each do |bet| %>  
					   <%= link_to(close_bet_path(bet), :class => "btn btn-primary") do %>
								<i class="icon-ok icon-white"></i> <%= bet.title %>
					   <% end %>
		      <% end %>
        </div>
      <% else %>
          <strong><%= user.name %> has <%= pluralize(user.expired_bets.count, 'bet') %> that needs to be closed !</strong>
      <% end %>



    <table>
      <tr>
        <th align="left">Title</th>
        <th align="left">Actions</th>
      </tr>
      <% user.expired_bets.each do |bet| %>
          <%= render :partial => 'show_bet', :locals => {:bet => bet} %>
      <% end %>
    </table>

<% end %>


<% if (user.open_bets.size > 0) %>
    <h2>Open Bets</h2>
    <table>
      <tr>
        <th align="left">Title</th>
        <th align="left">Actions</th>
      </tr>
      <% user.open_bets.each do |bet| %>
          <%= render :partial => 'show_bet', :locals => {:bet => bet} %>
      <% end %>
    </table>
<% end %>


<% if (user.closed_bets.count > 0) %>
    <h2>Closed Bets</h2>
    <table>
      <tr>
        <th align="left">Title</th>
        <th align="left">Actions</th>
      </tr>
      <% user.closed_bets.each do |bet| %>
          <%= render :partial => 'show_bet', :locals => {:bet => bet} %>
      <% end %>
    </table>
<% end %>


<% if user == current_user %>

    <% if (user.bets.count == 0) %>
        No bet created yet. <%= link_to "Create your first bet now !", new_bet_url %>
    <% else %>



        <% if (user.draft_bets.count > 0) %>
            <h2>Draft Bets</h2>
            <table>
              <tr>
                <th align="left">Title</th>
                <th align="left">Actions</th>
              </tr>
              <% user.draft_bets.each do |bet| %>
                  <%= render :partial => 'show_bet', :locals => {:bet => bet} %>
              <% end %>
            </table>
        <% end %>

    <% end %>

<% end %>

app/views/users/index.html.erb
<h1>Your account</h1>


<ul>

  <li><%= link_to 'Modify my info', edit_user_registration_path %></li>
  <li><%= link_to 'New Bet', new_bet_path %></li>

</ul>

<p>
  Your credit : <strong><%= pluralize(number_with_precision(current_user.brouzouf, :precision => 2) , "brouzouf") %></strong>
</p>

<h2>My Bets</h2>

<%= render :partial => 'show_bets', :locals => {:user => current_user} %>

<h2>My Bids</h2>
<ul>
  <% current_user.bids.each do |bid| %>
      <li> <%= I18n.l bid.created_at, :format => :short %> - <b><%= bid.choice.description %></b>
        on  <%= link_to bid.choice.bet.title, bid.choice.bet %> </li>
  <% end %>
</ul>

app/views/users/list.html.erb
<h1>Bidders list</h1>

<table>
    <tr>
      <th align="left">Bidder name</th>
      <th align="left">Bets created</th>
      <th align="left">Brouzouf</th>
    </tr>

  <% @bidders.each  do |user| %>
     <tr>
       <td><%= link_to user.name, user %></td>
       <td><%= user.bets.count %></td>
       <td><%= user.brouzouf %></td>
     </tr>

<% end %>

</table>

app/views/users/show.html.erb
<h1><%=@user.name%>'s Public Page</h1>
	

<h3><%= pluralize(number_with_precision(@user.brouzouf, :precision => 2), "Brouzouf" ) %> </h3>

<h2>Bets listing</h2>

<%= render :partial => 'show_bets', :locals => {:user => @user} %>