config/routes.rb
Brouzouf::Application.routes.draw do

  resources :bids

    
  resources :bets do
  
    member do
      post 'set_bet_open', 'set_bet_close', 'set_bet_creation', 'make_a_bid', 'close_bid'
      get  'close'
    end

    resources :choices, :only => [:new, :create, :update, :destroy, :edit]

  end

  get "home/index"

  devise_for :users do
  
    get 'users', :to => 'users#index', :as => :user_root # Rails 3
    match '/users/show/:id', :to => 'users#show',    :as => :user,         :via => :get
    #match '/users/list', :controller => '/list'
    match '/users/list' => 'users#list', :via => :get

  end

 # resources :users do
 #   collection do
 #     get 'list'
 #   end
 # end

  root :to => "home#index"

  
end

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta charset="utf-8" />
  <title>Brouzouf</title>


  <%= stylesheet_link_tag :application %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %> 
  <style> body {        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */      }    </style>          
</head>

<body>
 
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">   
		  	<%= link_to 'Brouzouf', root_path , :class => "brand" %>
		    <div class="nav-collapse">                                  
					<ul class="nav">
						<li><%= link_to 'Open Bets', root_path, :class => "active" %></li>
		        <li><%= link_to 'New Bet', new_bet_url %></li>
		        <% if user_signed_in? %>
		           <li><%= link_to 'My Bets', user_url(current_user) %></li>
		        <% end %> 
					</ul>
		      <ul class="nav pull-right">
						<% if user_signed_in? %>
	              <li>Hello <b><%= link_to current_user.name, user_root_path %></b></li>
	              <li class="divider-vertical"/>
								<li><%= link_to 'Sign out', destroy_user_session_path %> </li>
	          <% end %>
	          <% unless user_signed_in? %>
	             <li><%= link_to 'Sign In', new_user_session_path, :class => "small radius white button" %></li>
	             <li class="divider-vertical"/>
	             <li><%= link_to 'Sign Up', new_user_registration_path, :class => "small radius white button" %></li>
	          <% end %>
					</ul>
		  	</div>
			</div>
	  </div>
	</div>
  <div class="container">
	  <div class="row">
	 		<div class="span12">
	      <% flash.each do |k, v| %>
	          <!-- <%= k %> -->
	          <% if k == :notice
	                 k = "alert-success"
	             elsif k == :alert
	                 k = "alert-error"
	             end %>
	          <div class="alert <%= k %> fade in"><%= v %>
	            <a href="" class="close" data-dismiss="alert">&times;</a></div>
	      <% end %>
	                </div>
	      </div>
	          <div class="row">
	            <div class="twelve columns">

	      <%= yield %>
	      </div>
	    </div>      
    </div> 
    <!-- FOOTER -->   
		<hr>
    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="span4">
            <p><strong>Brouzouf</strong> is a social betting site.</p>      
            <p><em>Please report any issue <a href="https://github.com/mathieu/brouzouf/issues">here</a> !</em></p>

          </div>

          <div class="span4">
            <p>As you can see, <strong>Brouzouf</strong> is looking for a web <strong>Designer</strong>.</p><p> Thanks to <a href="http://twitter.github.com/bootstrap/">Boostrap</a> for the css.</p>
          </div>

          <div class="span4">
            <p>© 2011 <a href="https://github.com/mathieu/brouzouf">Brouzouf</a>. All rights reserved.</p>
          </div>
        </div>
      </div>
    </footer>
  </div> 

</body>
</html>